config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  # GET /kittens
  # GET /kittens.json
  def index
    @kittens = Kitten.all
    
    respond_to do |format|
      format.json { render :json => @kittens }
    end
  end

  # GET /kittens/1
  # GET /kittens/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render :json => Kitten.all.find(params[:id]) }
    end
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
  end

  # POST /kittens
  # POST /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten}
        flash[:alert] = 'Kitten was successfully created.'
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kittens/1
  # PATCH/PUT /kittens/1.json
  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to @kitten}
        flash[:alert] = 'Kitten was successfully updated.'
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kittens/1
  # DELETE /kittens/1.json
  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url}
      flash[:alert] = 'Kitten was successfully deleted.'
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(kitten) do |f| %>
  <% if kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
      <% kitten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :age %>
  <%= f.select :age, options_for_select((1..10)) %>
  
  <%= f.label :cuteness %>
  <%= f.select :cuteness, options_for_select((1..10)) %>
  
  <%= f.label :softness %>
  <%= f.select :softness, options_for_select((1..10)) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Editing Kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Show', @kitten %> |
<%= link_to 'Delete', @kitten, method: :delete %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= link_to kitten.name, kitten %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'Delete', kitten, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
    </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @kitten.name%></td>
    <td><%= @kitten.age %></td>
    <td><%= @kitten.cuteness %></td>
    <td><%= @kitten.softness %></td>
  </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %> |
<%= link_to 'Delete', @kitten, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |msg_type, msg| %>
  <%= content_tag(:div, msg) %>
<% end %>

<%= yield %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>